In [1]:
library(Seurat)
library(dplyr)
library(stringr)

Warning message:
“package ‘Seurat’ was built under R version 4.3.3”
Loading required package: SeuratObject

Warning message:
“package ‘SeuratObject’ was built under R version 4.3.3”
Loading required package: sp

Warning message:
“package ‘sp’ was built under R version 4.3.2”

Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, t


Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘stringr’ was built under R version 4.3.2”

In [2]:
plan("multicore", workers = 10)
options(future.globals.maxSize = 30000 * 1024^2)

In [ ]:
# "indir" is a custom input path, and "outdir" is a custom output path.
# indir=""
# outdir=""

In [ ]:
TSO_metadata <- read.csv("../../input/01-youth/RNA_DNA_match_name_QC_class_label.csv", row.names = 1)

In [4]:
TSO_metadata

                                                                  Unique_ID_match
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AACCAGAG     P49_Male_Hippo_TSO_plate1.AACCAGAG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AAGACACC     P49_Male_Hippo_TSO_plate1.AAGACACC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AAGACCGT     P49_Male_Hippo_TSO_plate1.AAGACCGT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGACCTTG     P49_Male_Hippo_TSO_plate1.AGACCTTG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGACGCTA     P49_Male_Hippo_TSO_plate1.AGACGCTA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCCTATC     P49_Male_Hippo_TSO_plate1.AGCCTATC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCGAGAT     P49_Male_Hippo_TSO_plate1.AGCGAGAT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCTAAGC     P49_Male_Hippo_TSO_plate1.AGCTAAGC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCTACCA     P49_Male_Hippo_TSO_plate1.AGCTACCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGGAACAC     P49_Male_Hippo_TSO_plate1.AGGAACAC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGGATAGC     P49_Male_Hippo_TSO_plate1.AGGATAGC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGTGACCT     P49_Male_Hippo_TSO_plate1.AGTGACCT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.ATAACGCC     P49_Male_Hippo_TSO_plate1.ATAACGCC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.ATCTGACC     P49_Male_Hippo_TSO_plate1.ATCTGACC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAACACAG     P49_Male_Hippo_TSO_plate1.CAACACAG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAACTCCA     P49_Male_Hippo_TSO_plate1.CAACTCCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAAGGTAC     P49_Male_Hippo_TSO_plate1.CAAGGTAC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAATAGCC     P49_Male_Hippo_TSO_plate1.CAATAGCC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAATGCGA     P49_Male_Hippo_TSO_plate1.CAATGCGA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CACAGACT     P49_Male_Hippo_TSO_plate1.CACAGACT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CACGCAAT     P49_Male_Hippo_TSO_plate1.CACGCAAT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAGGTTCA     P49_Male_Hippo_TSO_plate1.CAGGTTCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAGTGCTT     P49_Male_Hippo_TSO_plate1.CAGTGCTT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CATGAGCA     P49_Male_Hippo_TSO_plate1.CATGAGCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAAGGTT     P49_Male_Hippo_TSO_plate1.CCAAGGTT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCACAACA     P49_Male_Hippo_TSO_plate1.CCACAACA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAGTATC     P49_Male_Hippo_TSO_plate1.CCAGTATC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAGTTGA     P49_Male_Hippo_TSO_plate1.CCAGTTGA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCGCTTAA     P49_Male_Hippo_TSO_plate1.CCGCTTAA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCTTCCAT     P49_Male_Hippo_TSO_plate1.CCTTCCAT
⋮                                                                 ⋮
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAACCGA P56_Male_Striatum_TSO_plate70.GTAACCGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAAGGTG P56_Male_Striatum_TSO_plate70.GTAAGGTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACACCT P56_Male_Striatum_TSO_plate70.GTACACCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACCACA P56_Male_Striatum_TSO_plate70.GTACCACA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCAGTCA P56_Male_Striatum_TSO_plate70.GTCAGTCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCATCGT P56_Male_Striatum_TSO_plate70.GTCATCGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTAAG P56_Male_Striatum_TSO_plate70.GTCCTAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTTGA P56_Male_Striatum_TSO_plate70.GTCCTTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGATTG P56_Male_Striatum_TSO_plate70.GTCGATTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGTTAC P56_Male_Striatum_TSO_plate70.GTCGTTAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACCTGCA P56_Male_Striatum_TSO_plate70.TACCTGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACGGTCT P56_Male_Striatum_TSO_plate70.TACGGTCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACTCCAG P56_Male_Striatum_TSO_plate70.TACTCCAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TAGGAGCT P56_Male_Striatum_TSO_plate70.TAGGAGCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TATGGCAC P56_Male_Striatum_TSO_plate70.TATGGCAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCATCTCC P56_Male_Striatum_TSO_plate70.TCATCTCC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCACGTT P56_Male_Striatum_TSO_plate70.TCCACGTT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCATTGC P56_Male_Striatum_TSO_plate70.TCCATTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCTCATG P56_Male_Striatum_TSO_plate70.TCCTCATG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGGATTC P56_Male_Striatum_TSO_plate70.TCGGATTC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGTCTGA P56_Male_Striatum_TSO_plate70.TCGTCTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTACGCA P56_Male_Striatum_TSO_plate70.TCTACGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTAGGAG P56_Male_Striatum_TSO_plate70.TCTAGGAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGCGTAAC P56_Male_Striatum_TSO_plate70.TGCGTAAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGAAGCA P56_Male_Striatum_TSO_plate70.TGGAAGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGTGAAG P56_Male_Striatum_TSO_plate70.TGGTGAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACCGAC P56_Male_Striatum_TSO_plate70.TTACCGAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACGTGC P56_Male_Striatum_TSO_plate70.TTACGTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTCCAGGT P56_Male_Striatum_TSO_plate70.TTCCAGGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTGCGAGA P56_Male_Striatum_TSO_plate70.TTGCGAGA
                                                                  hmC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AACCAGAG     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AACCAGAG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AAGACACC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AAGACACC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AAGACCGT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AAGACCGT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGACCTTG     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGACCTTG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGACGCTA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGACGCTA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCCTATC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGCCTATC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCGAGAT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGCGAGAT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCTAAGC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGCTAAGC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCTACCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGCTACCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGGAACAC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGGAACAC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGGATAGC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGGATAGC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGTGACCT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.AGTGACCT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.ATAACGCC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.ATAACGCC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.ATCTGACC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.ATCTGACC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAACACAG     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CAACACAG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAACTCCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CAACTCCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAAGGTAC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CAAGGTAC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAATAGCC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CAATAGCC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAATGCGA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CAATGCGA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CACAGACT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CACAGACT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CACGCAAT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CACGCAAT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAGGTTCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CAGGTTCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAGTGCTT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CAGTGCTT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CATGAGCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CATGAGCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAAGGTT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CCAAGGTT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCACAACA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CCACAACA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAGTATC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CCAGTATC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAGTTGA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CCAGTTGA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCGCTTAA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CCGCTTAA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCTTCCAT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5mC_plate1.CCTTCCAT
⋮                                                                 ⋮
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAACCGA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAACCGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAAGGTG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAAGGTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACACCT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACACCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACCACA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACCACA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCAGTCA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCAGTCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCATCGT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCATCGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTAAG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTTGA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGATTG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGATTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGTTAC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGTTAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACCTGCA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACCTGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACGGTCT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACGGTCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACTCCAG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACTCCAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TAGGAGCT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TAGGAGCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TATGGCAC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TATGGCAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCATCTCC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCATCTCC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCACGTT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCACGTT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCATTGC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCATTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCTCATG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCTCATG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGGATTC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCGGATTC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGTCTGA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCGTCTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTACGCA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCTACGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTAGGAG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCTAGGAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGCGTAAC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGCGTAAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGAAGCA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGGAAGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGTGAAG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGGTGAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACCGAC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTACCGAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACGTGC P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTACGTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTCCAGGT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTCCAGGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTGCGAGA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTGCGAGA
                                                                  mC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AACCAGAG     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AACCAGAG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AAGACACC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AAGACACC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AAGACCGT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AAGACCGT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGACCTTG     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGACCTTG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGACGCTA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGACGCTA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCCTATC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGCCTATC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCGAGAT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGCGAGAT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCTAAGC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGCTAAGC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGCTACCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGCTACCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGGAACAC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGGAACAC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGGATAGC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGGATAGC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.AGTGACCT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.AGTGACCT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.ATAACGCC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.ATAACGCC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.ATCTGACC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.ATCTGACC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAACACAG     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CAACACAG
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAACTCCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CAACTCCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAAGGTAC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CAAGGTAC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAATAGCC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CAATAGCC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAATGCGA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CAATGCGA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CACAGACT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CACAGACT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CACGCAAT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CACGCAAT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAGGTTCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CAGGTTCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CAGTGCTT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CAGTGCTT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CATGAGCA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CATGAGCA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAAGGTT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CCAAGGTT
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCACAACA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CCACAACA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAGTATC     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CCAGTATC
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCAGTTGA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CCAGTTGA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCGCTTAA     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CCGCTTAA
P49_Male_230905Mouse1_Hippo_EXP230908_TSO_RNA_plate1.CCTTCCAT     P49_Male_230905Mouse1_Hippo_EXP230908_TSO_joint5hmC_plate1.CCTTCCAT
⋮                                                                 ⋮
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAACCGA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTAACCGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAAGGTG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTAAGGTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACACCT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTACACCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACCACA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTACCACA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCAGTCA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCAGTCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCATCGT P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCATCGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTAAG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCCTAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTTGA P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCCTTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGATTG P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCGATTG

In [5]:
TSO_QC_metadata <- subset(TSO_metadata ,total_QC == 1 )

In [6]:
TSO_QC_metadata

                                                                   Unique_ID_match
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AACCAGAG P49_Male_LeftCortex_TSO_plate1.AACCAGAG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AAGACACC P49_Male_LeftCortex_TSO_plate1.AAGACACC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AAGACCGT P49_Male_LeftCortex_TSO_plate1.AAGACCGT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGACCTTG P49_Male_LeftCortex_TSO_plate1.AGACCTTG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGACGCTA P49_Male_LeftCortex_TSO_plate1.AGACGCTA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCCTATC P49_Male_LeftCortex_TSO_plate1.AGCCTATC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCTAAGC P49_Male_LeftCortex_TSO_plate1.AGCTAAGC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCTACCA P49_Male_LeftCortex_TSO_plate1.AGCTACCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGGAACAC P49_Male_LeftCortex_TSO_plate1.AGGAACAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGGATAGC P49_Male_LeftCortex_TSO_plate1.AGGATAGC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGTGACCT P49_Male_LeftCortex_TSO_plate1.AGTGACCT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.ATAACGCC P49_Male_LeftCortex_TSO_plate1.ATAACGCC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.ATCTGACC P49_Male_LeftCortex_TSO_plate1.ATCTGACC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAACACAG P49_Male_LeftCortex_TSO_plate1.CAACACAG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAACTCCA P49_Male_LeftCortex_TSO_plate1.CAACTCCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAAGGTAC P49_Male_LeftCortex_TSO_plate1.CAAGGTAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAATAGCC P49_Male_LeftCortex_TSO_plate1.CAATAGCC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAATGCGA P49_Male_LeftCortex_TSO_plate1.CAATGCGA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CACAGACT P49_Male_LeftCortex_TSO_plate1.CACAGACT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CACGCAAT P49_Male_LeftCortex_TSO_plate1.CACGCAAT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGCATAC P49_Male_LeftCortex_TSO_plate1.CAGCATAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGGTTCA P49_Male_LeftCortex_TSO_plate1.CAGGTTCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGTGCTT P49_Male_LeftCortex_TSO_plate1.CAGTGCTT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CATGAGCA P49_Male_LeftCortex_TSO_plate1.CATGAGCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAAGGTT P49_Male_LeftCortex_TSO_plate1.CCAAGGTT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCACAACA P49_Male_LeftCortex_TSO_plate1.CCACAACA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAGTATC P49_Male_LeftCortex_TSO_plate1.CCAGTATC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAGTTGA P49_Male_LeftCortex_TSO_plate1.CCAGTTGA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCGCTTAA P49_Male_LeftCortex_TSO_plate1.CCGCTTAA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCTTCCAT P49_Male_LeftCortex_TSO_plate1.CCTTCCAT
⋮                                                                  ⋮
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAACCGA  P56_Male_Striatum_TSO_plate70.GTAACCGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAAGGTG  P56_Male_Striatum_TSO_plate70.GTAAGGTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACACCT  P56_Male_Striatum_TSO_plate70.GTACACCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACCACA  P56_Male_Striatum_TSO_plate70.GTACCACA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCAGTCA  P56_Male_Striatum_TSO_plate70.GTCAGTCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCATCGT  P56_Male_Striatum_TSO_plate70.GTCATCGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTAAG  P56_Male_Striatum_TSO_plate70.GTCCTAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTTGA  P56_Male_Striatum_TSO_plate70.GTCCTTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGATTG  P56_Male_Striatum_TSO_plate70.GTCGATTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGTTAC  P56_Male_Striatum_TSO_plate70.GTCGTTAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACCTGCA  P56_Male_Striatum_TSO_plate70.TACCTGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACGGTCT  P56_Male_Striatum_TSO_plate70.TACGGTCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACTCCAG  P56_Male_Striatum_TSO_plate70.TACTCCAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TAGGAGCT  P56_Male_Striatum_TSO_plate70.TAGGAGCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TATGGCAC  P56_Male_Striatum_TSO_plate70.TATGGCAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCATCTCC  P56_Male_Striatum_TSO_plate70.TCATCTCC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCACGTT  P56_Male_Striatum_TSO_plate70.TCCACGTT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCATTGC  P56_Male_Striatum_TSO_plate70.TCCATTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCTCATG  P56_Male_Striatum_TSO_plate70.TCCTCATG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGGATTC  P56_Male_Striatum_TSO_plate70.TCGGATTC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGTCTGA  P56_Male_Striatum_TSO_plate70.TCGTCTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTACGCA  P56_Male_Striatum_TSO_plate70.TCTACGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTAGGAG  P56_Male_Striatum_TSO_plate70.TCTAGGAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGCGTAAC  P56_Male_Striatum_TSO_plate70.TGCGTAAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGAAGCA  P56_Male_Striatum_TSO_plate70.TGGAAGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGTGAAG  P56_Male_Striatum_TSO_plate70.TGGTGAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACCGAC  P56_Male_Striatum_TSO_plate70.TTACCGAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACGTGC  P56_Male_Striatum_TSO_plate70.TTACGTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTCCAGGT  P56_Male_Striatum_TSO_plate70.TTCCAGGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTGCGAGA  P56_Male_Striatum_TSO_plate70.TTGCGAGA
                                                                   hmC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AACCAGAG P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AACCAGAG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AAGACACC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AAGACACC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AAGACCGT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AAGACCGT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGACCTTG P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGACCTTG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGACGCTA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGACGCTA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCCTATC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCCTATC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCTAAGC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCTAAGC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCTACCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCTACCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGGAACAC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGGAACAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGGATAGC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGGATAGC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGTGACCT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGTGACCT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.ATAACGCC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.ATAACGCC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.ATCTGACC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.ATCTGACC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAACACAG P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAACACAG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAACTCCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAACTCCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAAGGTAC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAAGGTAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAATAGCC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAATAGCC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAATGCGA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAATGCGA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CACAGACT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CACAGACT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CACGCAAT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CACGCAAT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGCATAC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGCATAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGGTTCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGGTTCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGTGCTT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGTGCTT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CATGAGCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CATGAGCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAAGGTT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAAGGTT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCACAACA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCACAACA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAGTATC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAGTATC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAGTTGA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAGTTGA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCGCTTAA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCGCTTAA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCTTCCAT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCTTCCAT
⋮                                                                  ⋮
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAACCGA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAACCGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAAGGTG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAAGGTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACACCT  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACACCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACCACA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACCACA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCAGTCA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCAGTCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCATCGT  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCATCGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTAAG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCCTTGA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGATTG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGATTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTCGTTAC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGTTAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACCTGCA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACCTGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACGGTCT  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACGGTCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TACTCCAG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACTCCAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TAGGAGCT  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TAGGAGCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TATGGCAC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TATGGCAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCATCTCC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCATCTCC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCACGTT  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCACGTT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCATTGC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCATTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCCTCATG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCTCATG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGGATTC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCGGATTC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCGTCTGA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCGTCTGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTACGCA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCTACGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TCTAGGAG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCTAGGAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGCGTAAC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGCGTAAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGAAGCA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGGAAGCA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TGGTGAAG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGGTGAAG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACCGAC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTACCGAC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTACGTGC  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTACGTGC
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTCCAGGT  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTCCAGGT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.TTGCGAGA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTGCGAGA
                                                                   mC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AACCAGAG P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AACCAGAG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AAGACACC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AAGACACC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AAGACCGT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AAGACCGT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGACCTTG P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGACCTTG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGACGCTA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGACGCTA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCCTATC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGCCTATC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCTAAGC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGCTAAGC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGCTACCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGCTACCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGGAACAC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGGAACAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGGATAGC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGGATAGC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.AGTGACCT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGTGACCT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.ATAACGCC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.ATAACGCC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.ATCTGACC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.ATCTGACC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAACACAG P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAACACAG
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAACTCCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAACTCCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAAGGTAC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAAGGTAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAATAGCC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAATAGCC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAATGCGA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAATGCGA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CACAGACT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CACAGACT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CACGCAAT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CACGCAAT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGCATAC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAGCATAC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGGTTCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAGGTTCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CAGTGCTT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAGTGCTT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CATGAGCA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CATGAGCA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAAGGTT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCAAGGTT
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCACAACA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCACAACA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAGTATC P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCAGTATC
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCAGTTGA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCAGTTGA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCGCTTAA P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCGCTTAA
P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_RNA_plate1.CCTTCCAT P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCTTCCAT
⋮                                                                  ⋮
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAACCGA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTAACCGA
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTAAGGTG  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTAAGGTG
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACACCT  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTACACCT
P56_Male_231218Mouse1_Striatum_EXP240120_TSO_RNA_plate70.GTACCACA  P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTACCACA

In [7]:
dim(TSO_QC_metadata)

[1] 44608    10

In [31]:
TSO_QC_df=TSO_QC_metadata[c("hmC","mC","subclass_label")]

In [ ]:
allc_hmC <- read.table("../../input/01-youth/TSO-joint-RNA_5hmC_allc_table_0820_47712cell.txt")
colnames(allc_hmC) <- c("hmC","AllcPath_hmC")
allc_hmC$hmC <- gsub("^allc_","",allc_hmC$hmC)

In [ ]:
allc_mC <- read.table("../../input/01-youth/TSO-joint-RNA_5mC_allc_table_0820_47712cell.txt")
colnames(allc_mC) <- c("mC","AllcPath_mC")
allc_mC$mC <- gsub("^allc_","",allc_mC$mC)

In [57]:
TSO_QC_df<-merge(TSO_QC_df,allc_hmC,by = "hmC",all=FALSE)
TSO_QC_df<-merge(TSO_QC_df,allc_mC,by = "mC",all=FALSE)

In [58]:
TSO_QC_df

      mC
1     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AACCAGAG
2     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AAGACACC
3     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AAGACCGT
4     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGACCTTG
5     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGACGCTA
6     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGCCTATC
7     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGCTAAGC
8     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGCTACCA
9     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGGAACAC
10    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGGATAGC
11    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.AGTGACCT
12    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.ATAACGCC
13    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.ATCTGACC
14    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAACACAG
15    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAACTCCA
16    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAAGGTAC
17    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAATAGCC
18    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAATGCGA
19    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CACAGACT
20    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CACGCAAT
21    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAGCATAC
22    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAGGTTCA
23    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CAGTGCTT
24    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CATGAGCA
25    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCAAGGTT
26    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCACAACA
27    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCAGTATC
28    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCAGTTGA
29    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCGCTTAA
30    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5mC_plate1.CCTTCCAT
⋮     ⋮
44579 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTAACCGA
44580 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTAAGGTG
44581 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTACACCT
44582 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTACCACA
44583 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCAGTCA
44584 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCATCGT
44585 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCCTAAG
44586 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCCTTGA
44587 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCGATTG
44588 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.GTCGTTAC
44589 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TACCTGCA
44590 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TACGGTCT
44591 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TACTCCAG
44592 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TAGGAGCT
44593 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TATGGCAC
44594 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCATCTCC
44595 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCCACGTT
44596 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCCATTGC
44597 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCCTCATG
44598 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCGGATTC
44599 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCGTCTGA
44600 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCTACGCA
44601 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TCTAGGAG
44602 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TGCGTAAC
44603 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TGGAAGCA
44604 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TGGTGAAG
44605 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TTACCGAC
44606 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TTACGTGC
44607 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TTCCAGGT
44608 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5mC_plate70.TTGCGAGA
      hmC
1     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AACCAGAG
2     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AAGACACC
3     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AAGACCGT
4     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGACCTTG
5     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGACGCTA
6     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCCTATC
7     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCTAAGC
8     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCTACCA
9     P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGGAACAC
10    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGGATAGC
11    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGTGACCT
12    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.ATAACGCC
13    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.ATCTGACC
14    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAACACAG
15    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAACTCCA
16    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAAGGTAC
17    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAATAGCC
18    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAATGCGA
19    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CACAGACT
20    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CACGCAAT
21    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGCATAC
22    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGGTTCA
23    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGTGCTT
24    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CATGAGCA
25    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAAGGTT
26    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCACAACA
27    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAGTATC
28    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAGTTGA
29    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCGCTTAA
30    P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCTTCCAT
⋮     ⋮
44579 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAACCGA
44580 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAAGGTG
44581 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACACCT
44582 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACCACA
44583 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCAGTCA
44584 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCATCGT
44585 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTAAG
44586 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTTGA
44587 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGATTG
44588 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGTTAC
44589 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACCTGCA
44590 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACGGTCT
44591 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACTCCAG
44592 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TAGGAGCT
44593 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TATGGCAC
44594 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCATCTCC
44595 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCACGTT
44596 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCATTGC
44597 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCCTCATG
44598 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCGGATTC
44599 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCGTCTGA
44600 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCTACGCA
44601 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TCTAGGAG
44602 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGCGTAAC
44603 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGGAAGCA
44604 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TGGTGAAG
44605 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTACCGAC
44606 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTACGTGC
44607 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTCCAGGT
44608 P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TTGCGAGA
      subclass_label
1     L4/5 IT CTX Glut
2     CLA-EPd-CTX Car3 Glut
3     L4 RSP-ACA Glut
4     L6 CT CTX Glut
5     L4/5 IT CTX Glut
6     L2/3 IT CTX Glut
7     L4/5 IT CTX Glut
8     L4/5 IT CTX Glut
9     L4/5 IT CTX Glut
10    L6 CT CTX Glut
11    L2/3 IT CTX Glut
12    L2/3 IT CTX Glut
13    L2/3 IT CTX Glut
14    L4/5 IT CTX Glut
15    L4/5 IT CTX Glut
16    L2/3 IT CTX Glut
17    L4/5 IT CTX Glut
18    L5 IT CTX Glut
19    L2/3 IT CTX Glut
20    L5 IT CTX Glut
21    Astro-TE NN
22    L2/3 IT CTX Glut
23    Astro-TE NN
24    L2/3 IT CTX Glut
25    L5 ET CTX Glut
26    Microglia NN
27    Oligo NN
28    Astro-TE NN
29    STR D1 Gaba
30    L5 IT CTX Glut
⋮     ⋮
44579 STR D1 Gaba
44580 STR D1 Gaba
44581 STR D1 Gaba
44582 Oligo NN
44583 STR D1 Gaba
44584 STR D1 Gaba
44585 STR D1 Gaba
44586 STR D1 Gaba
44587 STR D1 Gaba
44588 STR D1 Gaba
44589 STR D1 Gaba
44590 STR D1 Gaba
44591 STR D1 Gaba
44592 STR D1 Gaba
44593 STR D1 Gaba
44594 STR D1 Gaba
44595 STR D1 Gaba
44596 STR D1 Gaba
44597 STR D1 Gaba
44598 STR D1 Gaba
44599 STR D1 Gaba
44600 STR D1 Gaba
44601 STR D1 Gaba
44602 STR D1 Gaba
44603 STR D1 Gaba
44604 STR D1 Gaba
44605 STR D1 Gaba
44606 STR D1 Gaba
44607 STR D1 Gaba
44608 STR D1 Gaba
      AllcPath_hmC
1     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AACCAGAG.mm10.dna.tsv.gz
2     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AAGACACC.mm10.dna.tsv.gz
3     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AAGACCGT.mm10.dna.tsv.gz
4     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGACCTTG.mm10.dna.tsv.gz
5     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGACGCTA.mm10.dna.tsv.gz
6     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCCTATC.mm10.dna.tsv.gz
7     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCTAAGC.mm10.dna.tsv.gz
8     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGCTACCA.mm10.dna.tsv.gz
9     /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGGAACAC.mm10.dna.tsv.gz
10    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGGATAGC.mm10.dna.tsv.gz
11    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.AGTGACCT.mm10.dna.tsv.gz
12    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.ATAACGCC.mm10.dna.tsv.gz
13    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.ATCTGACC.mm10.dna.tsv.gz
14    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAACACAG.mm10.dna.tsv.gz
15    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAACTCCA.mm10.dna.tsv.gz
16    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAAGGTAC.mm10.dna.tsv.gz
17    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAATAGCC.mm10.dna.tsv.gz
18    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAATGCGA.mm10.dna.tsv.gz
19    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CACAGACT.mm10.dna.tsv.gz
20    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CACGCAAT.mm10.dna.tsv.gz
21    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGCATAC.mm10.dna.tsv.gz
22    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGGTTCA.mm10.dna.tsv.gz
23    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CAGTGCTT.mm10.dna.tsv.gz
24    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CATGAGCA.mm10.dna.tsv.gz
25    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAAGGTT.mm10.dna.tsv.gz
26    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCACAACA.mm10.dna.tsv.gz
27    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAGTATC.mm10.dna.tsv.gz
28    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCAGTTGA.mm10.dna.tsv.gz
29    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCGCTTAA.mm10.dna.tsv.gz
30    /share/analysisdata/Methyl/Data_run/yuan_20240504_nova_P49_P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P49_Male_240416Mouses_LeftCortex_EXP240419_TSO_joint5hmC_plate1.CCTTCCAT.mm10.dna.tsv.gz
⋮     ⋮
44579 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAACCGA.mm10.dna.tsv.gz
44580 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTAAGGTG.mm10.dna.tsv.gz
44581 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACACCT.mm10.dna.tsv.gz
44582 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTACCACA.mm10.dna.tsv.gz
44583 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCAGTCA.mm10.dna.tsv.gz
44584 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCATCGT.mm10.dna.tsv.gz
44585 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTAAG.mm10.dna.tsv.gz
44586 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCCTTGA.mm10.dna.tsv.gz
44587 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGATTG.mm10.dna.tsv.gz
44588 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.GTCGTTAC.mm10.dna.tsv.gz
44589 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACCTGCA.mm10.dna.tsv.gz
44590 /share/analysisdata/Methyl/Data_run/yuan_20240208_nova_P56-P540-Mouse1-TSO-joint-5hmC-5mC-RNA/DNA/Output_s1/bismark_allc/allc_P56_Male_231218Mouse1_Striatum_EXP240120_TSO_joint5hmC_plate70.TACGGTCT.mm10.dna.tsv.gz

In [59]:
TSO_QC_df_split=split(TSO_QC_df, TSO_QC_df$subclass_label)

In [60]:
names(TSO_QC_df_split)

 [1] "ACB-BST-FS D1 Gaba"    "Astro-TE NN"           "CA1-ProS Glut"
 [4] "CA3 Glut"              "CLA-EPd-CTX Car3 Glut" "DG Glut"
 [7] "L2/3 IT CTX Glut"      "L2/3 IT RSP Glut"      "L4 RSP-ACA Glut"
[10] "L4/5 IT CTX Glut"      "L5 ET CTX Glut"        "L5 IT CTX Glut"
[13] "L5 NP CTX Glut"        "L6 CT CTX Glut"        "Lamp5 Gaba"
[16] "Microglia NN"          "OB Dopa-Gaba"          "OB Eomes Ms4a15 Glut"
[19] "OB-in Frmd7 Gaba"      "OB-out Frmd7 Gaba"     "OB-STR-CTX Inh IMN"
[22] "OEC NN"                "Oligo NN"              "OPC NN"
[25] "Pvalb Gaba"            "Sncg Gaba"             "Sst Gaba"
[28] "STR D1 Gaba"           "STR D2 Gaba"           "SUB-ProS Glut"

In [ ]:
# iterate over all subclass
for (i in names(TSO_QC_df_split)) {
  # get the allc_path for the current subclass
  allc_paths <- TSO_QC_df_split[[i]]$AllcPath_hmC
  # generate the filename for saving
  file_name <- paste0(indir,"/5hmC_",gsub("[ /]", ".", i), ".txt")
  # do the saving
  write.table(allc_paths, file = file_name, row.names = FALSE, col.names = FALSE,quote = FALSE)
  cat("Saved", file_name, "\n")
    
  # the same procedure for 5mC instead of 5hmC
  allc_paths <- TSO_QC_df_split[[i]]$AllcPath_mC
  file_name <- paste0(indir,"/5mC_",gsub("[ /]", ".", i), ".txt")
  write.table(allc_paths, file = file_name, row.names = FALSE, col.names = FALSE,quote = FALSE)
  cat("Saved", file_name, "\n")
}

Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_ACB-BST-FS.D1.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_ACB-BST-FS.D1.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_Astro-TE.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_Astro-TE.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_CA1-ProS.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_CA1-ProS.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_CA3.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_CA3.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_CLA-EPd-CTX.Car3.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_CLA-EPd-CTX.Car3.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_DG.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_DG.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L2.3.IT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L2.3.IT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L2.3.IT.RSP.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L2.3.IT.RSP.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L4.RSP-ACA.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L4.RSP-ACA.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L4.5.IT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L4.5.IT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L5.ET.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L5.ET.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L5.IT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L5.IT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L5.NP.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L5.NP.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_L6.CT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_L6.CT.CTX.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_Lamp5.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_Lamp5.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_Microglia.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_Microglia.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_OB.Dopa-Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_OB.Dopa-Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_OB.Eomes.Ms4a15.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_OB.Eomes.Ms4a15.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_OB-in.Frmd7.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_OB-in.Frmd7.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_OB-out.Frmd7.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_OB-out.Frmd7.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_OB-STR-CTX.Inh.IMN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_OB-STR-CTX.Inh.IMN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_OEC.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_OEC.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_Oligo.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_Oligo.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_OPC.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_OPC.NN.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_Pvalb.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_Pvalb.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_Sncg.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_Sncg.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_Sst.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_Sst.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_STR.D1.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_STR.D1.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_STR.D2.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_STR.D2.Gaba.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5hmC/5hmC_SUB-ProS.Glut.txt
Saved /share/home/renlh/ll/DMR/01_merge_allc/allc_txt/subclass/5mC/5mC_SUB-ProS.Glut.txt