In [1]:
import anndata

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# "indir" is a custom input path, and "outdir" is a custom output path.
# indir=""
# outdir=""

In [ ]:
adata_5mCG = anndata.read_h5ad(f'{indir}/5mCG_frac_segment_by_cell.h5ad')

In [ ]:
adata_5hmCG = anndata.read_h5ad(f'{indir}/5hmCG_frac_segment_by_cell.h5ad')

In [5]:
adata_5mCG

AnnData object with n_obs × n_vars = 47712 × 2104791
    var: 'chrom', 'end', 'start'

In [38]:
adata_5hmCG

AnnData object with n_obs × n_vars = 47712 × 1777377
    var: 'chrom', 'end', 'start'

In [14]:
adata_5mCG.X

array([[nan, nan, nan, ..., nan, nan,  1.],
       [nan, nan, nan, ...,  1., nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan,  1.,  1., ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

In [39]:
adata_5hmCG.X

array([[nan,  0., nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [ 0., nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan,  0.],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

In [15]:
adata_5mCG.obs_names

Index(['allc_P49_Male_240416Mouses_LeftHippo_EXP240421_TSO_joint5mC_plate5.CAATAGCC',
       'allc_P49_Male_240416Mouses_LeftHippo_EXP240421_TSO_joint5mC_plate5.ATAACGCC',
       'allc_P49_Male_240416Mouses_LeftHippo_EXP240421_TSO_joint5mC_plate5.CCTTCCAT',
       'allc_P49_Male_240416Mouses_RightHippo_EXP240419_TSO_joint5mC_plate3.TCATCTCC',
       'allc_P49_Male_240416Mouses_RightHippo_EXP240419_TSO_joint5mC_plate3.GACGTCAT',
       'allc_P49_Male_240416Mouses_RightHippo_EXP240420_TSO_joint5mC_plate4.CTTGCTAG',
       'allc_P49_Male_240416Mouses_RightHippo_EXP240419_TSO_joint5mC_plate3.TCGGATTC',
       'allc_P49_Male_240416Mouses_LeftCortex_EXP240421_TSO_joint5mC_plate5.CTTCGGTT',
       'allc_P49_Male_240416Mouses_LeftCortex_EXP240421_TSO_joint5mC_plate5.CTGTACCA',
       'allc_P49_Male_240416Mouses_LeftCortex_EXP240420_TSO_joint5mC_plate4.GGCAAGTT',
       ...
       'allc_P56_Male_231204Mouse1_DeepCortex_EXP240104_TSO_joint5mC_plate71.AGCGAGAT',
       'allc_P56_Male_231218Mouse1_Striatum_EXP240108_TSO_joint5mC_plate54.AGCGAGAT',
       'allc_P56_Male_231204Mouse1_DeepCortex_EXP240104_TSO_joint5mC_plate76.AGCCTATC',
       'allc_P56_Male_231218Mouse1_Hippo_EXP240102_TSO_joint5mC_plate54.CGAGAGAA',
       'allc_P56_Male_231204Mouse1_DeepCortex_EXP240105_TSO_joint5mC_plate79.TCCACGTT',
       'allc_P56_Male_231218Mouse1_Hippo_EXP231228_TSO_joint5mC_plate41.AGCCTATC',
       'allc_P56_Male_231204Mouse1_DeepCortex_EXP240104_TSO_joint5mC_plate77.AGCGAGAT',
       'allc_P56_Male_231218Mouse1_Striatum_EXP240108_TSO_joint5mC_plate53.GCCTTAAC',
       'allc_P56_Male_231218Mouse1_Striatum_EXP240109_TSO_joint5mC_plate64.TGCGTAAC',
       'allc_P56_Male_231218Mouse1_Striatum_EXP240109_TSO_joint5mC_plate59.CATGAGCA'],
      dtype='object', name='cell', length=47712)

In [16]:
adata_5mCG.var_names

Index(['chr1_3000826_3001630', 'chr1_3003225_3003583', 'chr1_3003720_3004531',
       'chr1_3007429_3007581', 'chr1_3008544_3010494', 'chr1_3010819_3012306',
       'chr1_3013931_3014700', 'chr1_3014973_3015985', 'chr1_3016706_3017737',
       'chr1_3018491_3019022',
       ...
       'chr19_61316705_61317702', 'chr19_61317869_61318703',
       'chr19_61319797_61320884', 'chr19_61321193_61321384',
       'chr19_61321619_61322729', 'chr19_61323671_61324185',
       'chr19_61325280_61325656', 'chr19_61326706_61327126',
       'chr19_61330072_61330238', 'chr19_61330510_61331129'],
      dtype='object', name='segment', length=2104791)

In [22]:
df_5mCG=adata_5mCG.to_df().T

In [41]:
df_5hmCG=adata_5hmCG.to_df().T

In [23]:
df_5mCG

cell,allc_P49_Male_240416Mouses_LeftHippo_EXP240421_TSO_joint5mC_plate5.CAATAGCC,allc_P49_Male_240416Mouses_LeftHippo_EXP240421_TSO_joint5mC_plate5.ATAACGCC,allc_P49_Male_240416Mouses_LeftHippo_EXP240421_TSO_joint5mC_plate5.CCTTCCAT,allc_P49_Male_240416Mouses_RightHippo_EXP240419_TSO_joint5mC_plate3.TCATCTCC,allc_P49_Male_240416Mouses_RightHippo_EXP240419_TSO_joint5mC_plate3.GACGTCAT,allc_P49_Male_240416Mouses_RightHippo_EXP240420_TSO_joint5mC_plate4.CTTGCTAG,allc_P49_Male_240416Mouses_RightHippo_EXP240419_TSO_joint5mC_plate3.TCGGATTC,allc_P49_Male_240416Mouses_LeftCortex_EXP240421_TSO_joint5mC_plate5.CTTCGGTT,allc_P49_Male_240416Mouses_LeftCortex_EXP240421_TSO_joint5mC_plate5.CTGTACCA,allc_P49_Male_240416Mouses_LeftCortex_EXP240420_TSO_joint5mC_plate4.GGCAAGTT,...,allc_P56_Male_231204Mouse1_DeepCortex_EXP240104_TSO_joint5mC_plate71.AGCGAGAT,allc_P56_Male_231218Mouse1_Striatum_EXP240108_TSO_joint5mC_plate54.AGCGAGAT,allc_P56_Male_231204Mouse1_DeepCortex_EXP240104_TSO_joint5mC_plate76.AGCCTATC,allc_P56_Male_231218Mouse1_Hippo_EXP240102_TSO_joint5mC_plate54.CGAGAGAA,allc_P56_Male_231204Mouse1_DeepCortex_EXP240105_TSO_joint5mC_plate79.TCCACGTT,allc_P56_Male_231218Mouse1_Hippo_EXP231228_TSO_joint5mC_plate41.AGCCTATC,allc_P56_Male_231204Mouse1_DeepCortex_EXP240104_TSO_joint5mC_plate77.AGCGAGAT,allc_P56_Male_231218Mouse1_Striatum_EXP240108_TSO_joint5mC_plate53.GCCTTAAC,allc_P56_Male_231218Mouse1_Striatum_EXP240109_TSO_joint5mC_plate64.TGCGTAAC,allc_P56_Male_231218Mouse1_Striatum_EXP240109_TSO_joint5mC_plate59.CATGAGCA
segment,,,,,,,,,,,,,,,,,,,,,
chr1_3000826_3001630,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_3003225_3003583,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
chr1_3003720_3004531,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN
chr1_3007429_3007581,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_3008544_3010494,NaN,NaN,NaN,1.0,0.4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr19_61323671_61324185,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0,NaN,NaN
chr19_61325280_61325656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr19_61326706_61327126,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
chr19_61330072_61330238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr19_61330510_61331129,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [42]:
df_5hmCG

cell,allc_P56_Male_231211Mouse1_Striatum_EXP231215_TSO_joint5hmC_plate34.GTCAGTCA,allc_P56_Male_231211Mouse1_Striatum_EXP231215_TSO_joint5hmC_plate34.AGTGACCT,allc_P56_Male_231211Mouse1_Striatum_EXP231215_TSO_joint5hmC_plate34.CTCAGAAG,allc_P56_Male_231211Mouse1_Striatum_EXP231215_TSO_joint5hmC_plate34.CATGAGCA,allc_P56_Male_231211Mouse1_Striatum_EXP231215_TSO_joint5hmC_plate34.GGACATCA,allc_P56_Male_231204Mouse1_DeepCortex_EXP231214_TSO_joint5hmC_384plate9.ACAGCACCGT,allc_P56_Male_231204Mouse1_DeepCortex_EXP231214_TSO_joint5hmC_384plate9.ACCATGTTGC,allc_P56_Male_231127Mouse1_DeepCortex_EXP231211_TSO_joint5hmC_plate54.TCCATTGC,allc_P56_Male_231211Mouse1_Striatum_EXP231215_TSO_joint5hmC_plate34.GAACGGTT,allc_P56_Male_231211Mouse1_Striatum_EXP231215_TSO_joint5hmC_plate34.GAGAGTAC,...,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate47.AAGACCGT,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate46.CTTGCTAG,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate47.AGACCTTG,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate46.CAGGTTCA,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate46.TCTAGGAG,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate47.CCAAGGTT,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate47.CGAGAGAA,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate47.GGTATAGG,allc_P49_Male_240702Mouses_LeftCortex_EXP240714_TSO_joint5hmC_plate35.AACCAGAG,allc_P49_Male_240702Mouses_LeftCortex_EXP240715_TSO_joint5hmC_plate47.TCCTCATG
segment,,,,,,,,,,,,,,,,,,,,,
chr1_3000826_3001630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN
chr1_3003225_3003380,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN
chr1_3003720_3003899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_3004529_3006188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN
chr1_3008544_3009073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.0,NaN,0.000000,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr19_61326952_61328153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,NaN,0.000000
chr19_61329595_61329910,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.333333
chr19_61329973_61330074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN
chr19_61330083_61330182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.333333,NaN,NaN,0.333333,NaN,NaN,NaN,NaN,NaN
chr19_61330185_61331129,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN

In [43]:
#空出点内存
del adata_5mCG

In [26]:
df_5mCG.index.str.startswith("chr1_")

array([ True,  True,  True, ..., False, False, False])

In [44]:
df_5hmCG.index.str.startswith("chr1_")

array([ True,  True,  True, ..., False, False, False])

In [ ]:
df_5mCG

In [ ]:
for chr_number in range(1,20,1):
    temp_df=df_5mCG[df_5mCG.index.str.startswith(f"chr{chr_number}_")]
    temp_adata = anndata.AnnData(temp_df.T)
    temp_adata.write(f'{outdir}/5mCG_frac_segment_by_cell_chr{chr_number}.h5ad')
    temp_df=df_5hmCG[df_5hmCG.index.str.startswith(f"chr{chr_number}_")]
    temp_adata = anndata.AnnData(temp_df.T)
    temp_adata.write(f'{outdir}/5hmCG_frac_segment_by_cell_chr{chr_number}.h5ad')

In [29]:
temp_adata

AnnData object with n_obs × n_vars = 155916 × 47712

In [30]:
%%bash
pwd

/share/home/renlh/analysis/TSO/DMR/05_read_h5ad